In [2]:
import numpy as np

The Basic

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
# a.shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int64')

In [10]:
# Get Size
a.itemsize

8

In [13]:
# Get total size
#a.size * a.itemsize
a.nbytes

24