In [1]:
import numpy as np

Accessing/Changing specific elements, rows, columns, etc

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a.shape

(2, 7)

In [4]:
# Get a specific element [row, column]
a[1, 5]

np.int64(13)

In [5]:
a[1,-2]

np.int64(13)

In [6]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [10]:
# Getting a little more fance [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [11]:
# Change element '13' to 20
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# Change 3rd column with 5s
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [13]:
# Change 4th column with 1, 2
a[:,3] = [1,2]
print(a)

[[ 1  2  5  1  5  6  7]
 [ 8  9  5  2 12 20 14]]


3-D example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,6]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 6]]]


In [ ]:
# Get specific element (work outside in) {we want 4}
b[0,1,1] #1st, 2nd, 2nd

np.int64(4)

In [19]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
