In [2]:
import numpy as np

Initializing Different Types of Arrays

In [3]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
# Any other number matrix ((shape), value)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
# Any other number (full_like) {rehttps://www.youtube.com/watch?v=QUT1VHiLmmI-use array}
# (shape of, value)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers (rows, columns)
np.random.rand(4,2)

array([[0.40382182, 0.44854211],
       [0.03858475, 0.17364489],
       [0.31483779, 0.27342615],
       [0.70895367, 0.76825304]])

In [16]:
# Random Integer values (start value, size=(rows, columns))
np.random.randint(9, size=(3,4))

array([[1, 4, 6, 3],
       [5, 3, 8, 1],
       [5, 7, 6, 0]])

In [17]:
# Random Integer values (start value, size=(rows, columns))
# from 3 to 9
np.random.randint(3,9, size=(3,4))

array([[3, 4, 6, 3],
       [8, 3, 7, 4],
       [7, 6, 7, 6]])

In [19]:
# Identity matrix (rowsXcolumns)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat array np.repeat(arr, x_times)
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [26]:
# repeat 2d array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
# Exercise 
z = np.ones((1,5,5))
z[0,1,1:4] = 0
z[0,2,(1,3)] = 0
z[0,2,2] = 9
z[0,3,1:4] = 0
print(z)

[[[1. 1. 1. 1. 1.]
  [1. 0. 0. 0. 1.]
  [1. 0. 9. 0. 1.]
  [1. 0. 0. 0. 1.]
  [1. 1. 1. 1. 1.]]]


In [7]:
# Tutorial Solution for excercise
output = np.ones((5,5))
print(output)

j = np.zeros((3,3))
j[1,1] = 9
print(j)

output[1:4,1:4] = j
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays!!!!

In [10]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [11]:
b[0] = 100
print(b)

[100   2   3]


In [ ]:
print(a) # a becomes changed like b

[100   2   3]


In [14]:
# solution to copy array without changing original
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]
