In [1]:
import numpy as np

# Mathematics

In [9]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
a += 2
a

array([3, 4, 5, 6])

In [10]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [11]:
a ** 2

array([ 1,  4,  9, 16])

##### <u>Take the sin/cos/tan</u>

In [13]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

###### For more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
https://docs.scipy.org/doc/numpy/reference/routines.math.html

# Linear Algebra

##### <u>Multiplication</u>

In [5]:
# For multiplication, rows of 1st = columns of 2nd
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

##### <u>Find the determinant</u>

In [ ]:
# ID matrix has determinant of 1
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

##### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

##### Determinant
##### Trace
##### Singular Vector Decomposition
##### Eigenvalues
##### Matrix Norm
##### Inverse
##### Etc...

# Statistics

In [10]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

##### Minimum

In [11]:
np.min(stats)

np.int64(1)

##### Minimum based on row

In [ ]:
np.min(stats, axis=1) # 0 row (side) # 1 column (down)

array([1, 4])

##### Maximum

In [14]:
np.max(stats)

np.int64(6)

##### Sum

In [15]:
np.sum(stats, axis=0)

array([5, 7, 9])