In [1]:
import numpy as np

# Mathematics

In [9]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
a += 2
a

array([3, 4, 5, 6])

In [10]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [11]:
a ** 2

array([ 1,  4,  9, 16])

# Take the sin/cos/tan

In [13]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

###### For more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
https://docs.scipy.org/doc/numpy/reference/routines.math.html