In [1]:
import numpy as np

##### Reshaping Matrix

In [5]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before) # 2x4

after = before.reshape((8,1))
print(after)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### Vertically stacking Vectors

In [8]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

stack1 = np.vstack([v1,v2])
stack2 = np.vstack([v1,v2,v1,v2])

print(stack1)
print(stack2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


##### Horizontal stack

In [11]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])