In [1]:
import numpy as np

##### <u>Load Data from File</u>

In [ ]:
fileData = np.genfromtxt('data.txt', delimiter=',')
fileData #float

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [9]:
fileData = fileData.astype('int32') #int
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### <u> Boolean Masking and Advanced Indexing

In [10]:
# where in fileData is value > 50
fileData > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [11]:
# indexing where its greater than 50
fileData[fileData > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
# Index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
# axes 0 = downwards, axes 1 = side
np.any(fileData > 50, axis=0) # which columns

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
((fileData > 50) & (fileData < 100)) 

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [16]:
# reverse
(~((fileData > 50) & (fileData < 100)) )

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

# Quiz

In [18]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],
              [16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [44]:
a[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])